on:
  issues:
    types: [opened, edited]
jobs:
  issues-ql:
    runs-on: ubuntu-latest
    name: Issues Quality Linter
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Run Issues QL
        id: issues-ql
        uses: ./
